apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels: {{ toYaml .Values.operator.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: immudb
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: immudb
    spec:
      serviceAccountName: {{ .Chart.Name }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          resources: {{ toYaml .Values.operator.resources | nindent 12 }}